language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t erika/docker-react -f Dockerfile.dev .


script:
  - docker run -e CI=true erika/docker-react npm run test

# elasticbeanstalk
#deploy:
#  provider: elasticbeanstalk
#  region: "us-west-2"
#  app: "docker"
#  env: "Docker-env"
#  bucket_name: "elasticbeanstallk-us-west-2-2-34667788895"
#  bucket_path: "docker"
#  on:
#    branch: master
#  access_key_id: $AWS_ACCESS_KEY
#  secret_access_key: $AWS_SECRET_KEY
